<Type Name="EventDeliveryFailedException" FullName="System.Workflow.Activities.EventDeliveryFailedException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="48b889544946a903dd75b269a8b9f2adb8827aff" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="ja-JP" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
    <Meta Name="ms.locfileid" Value="30676686" />
  </Metadata>
  <TypeSignature Language="C#" Value="public sealed class EventDeliveryFailedException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit EventDeliveryFailedException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.Workflow.Activities.EventDeliveryFailedException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class EventDeliveryFailedException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class EventDeliveryFailedException sealed : SystemException" />
  <AssemblyInfo>
    <AssemblyName>System.Workflow.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="4cf72-101">ホストから発生したイベントをワークフロー インスタンスに配信できないときにスローされる例外です。</span>
      <span class="sxs-lookup">
        <span data-stu-id="4cf72-101">The exception that is thrown when an event that is raised from the host cannot be delivered to the workflow instance.</span>
      </span>
      <span data-ttu-id="4cf72-102">通常、イベントは、ワークフロー インスタンスの <see cref="T:System.Workflow.Activities.ExternalDataExchangeService" /> から発生します。</span>
      <span class="sxs-lookup">
        <span data-stu-id="4cf72-102">Typically the event is raised from an <see cref="T:System.Workflow.Activities.ExternalDataExchangeService" /> on a workflow instance.</span>
      </span>
      <span data-ttu-id="4cf72-103">このクラスは継承できません。</span>
      <span class="sxs-lookup">
        <span data-stu-id="4cf72-103">This class cannot be inherited.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
  
> [!NOTE]
>  [!INCLUDE[DeprecatedContent](~/includes/deprecatedcontent-md.md)]  
  
 <span data-ttu-id="4cf72-104">この例外がスローされると、"インスタンス ID "{2}" のインターフェイス型 "{0}" のイベント "{1}" は配信できません。" という文字列がイベント ログに追加されます。</span><span class="sxs-lookup"><span data-stu-id="4cf72-104">The following string is added to the event log when this exception is thrown: Event "{1}" on interface type "{0}" for instance id "{2}" cannot be delivered.</span></span>  
  
 <span data-ttu-id="4cf72-105">ステート マシン ワークフローを使用すると、"キュー '{0}' は有効ではありません" というメッセージを含む例外が発生する場合があります。</span><span class="sxs-lookup"><span data-stu-id="4cf72-105">When using a state machine workflow, you might get an exception with the message "Queue '{0}' is not enabled."</span></span> <span data-ttu-id="4cf72-106">これは、ステート マシンの現在の状態では特定のイベントの処理方法を識別できないときに起こります。</span><span class="sxs-lookup"><span data-stu-id="4cf72-106">This happens when the current state of the state machine does not know how to handle a specific event.</span></span> <span data-ttu-id="4cf72-107">たとえば、現在の状態以外の状態に、キュー '{0}' で表現される <xref:System.Workflow.Activities.EventDrivenActivity> を含む <xref:System.Workflow.Activities.HandleExternalEventActivity> が含まれている場合です。</span><span class="sxs-lookup"><span data-stu-id="4cf72-107">For example, when some state other than the current state contains the <xref:System.Workflow.Activities.EventDrivenActivity> that contains the <xref:System.Workflow.Activities.HandleExternalEventActivity> that is represented by the queue '{0}'.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="4cf72-108">
            <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-108">Initializes a new instance of the <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="4cf72-109">
            <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-109">Initializes a new instance of the <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> class.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4cf72-110">例外の原因を説明するエラー メッセージ。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-110">An error message that explains the reason for the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4cf72-111">例外の理由を説明するエラー メッセージを使用して、<see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-111">Initializes a new instance of the <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> class by using the error message that explains the reason for the exception.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4cf72-112">例外の原因を説明するエラー メッセージ。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-112">An error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="4cf72-113">この例外の原因となった <see cref="T:System.Exception" />。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-113">The <see cref="T:System.Exception" /> that caused this exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4cf72-114">例外の理由を説明するエラー メッセージおよびこの例外の原因となった <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> を使用して、<see cref="T:System.Exception" /> クラスの新しいインスタンスを初期化します。</span>
          <span class="sxs-lookup">
            <span data-stu-id="4cf72-114">Initializes a new instance of the <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" /> class by using the error message that explains the reason for the exception and the <see cref="T:System.Exception" /> that caused this exception.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>